const signInTab=document.getElementById("signInTab"),createAccountTab=document.getElementById("createAccountTab"),loginForm=document.getElementById("loginForm"),signupForm=document.getElementById("signupForm"),authTitle=document.getElementById("authTitle"),authSubtitle=document.getElementById("authSubtitle"),authFooter=document.getElementById("authFooter"),authMessage=document.getElementById("authMessage");
function showMessage(message,type=""){authMessage.textContent=message;authMessage.className=`auth-message ${type}`}
function bindFooter(){document.getElementById("footerSwitchBtn").addEventListener("click",signupForm.classList.contains("hidden")?showCreateAccount:showSignIn)}
function showSignIn(){signInTab.classList.add("active");createAccountTab.classList.remove("active");loginForm.classList.remove("hidden");signupForm.classList.add("hidden");authTitle.textContent="Welcome back";authSubtitle.textContent="Sign in to continue to your logistics dashboard.";authFooter.innerHTML='New to Routa? <button type="button" id="footerSwitchBtn">Create an account</button>';showMessage("");bindFooter()}
function showCreateAccount(){createAccountTab.classList.add("active");signInTab.classList.remove("active");signupForm.classList.remove("hidden");loginForm.classList.add("hidden");authTitle.textContent="Create your account";authSubtitle.textContent="Set up your Routa account to manage logistics operations.";authFooter.innerHTML='Already have an account? <button type="button" id="footerSwitchBtn">Sign in</button>';showMessage("");bindFooter()}
signInTab.addEventListener("click",showSignIn);createAccountTab.addEventListener("click",showCreateAccount);
function setupPasswordToggle(buttonId,inputId){const b=document.getElementById(buttonId),i=document.getElementById(inputId);b.addEventListener("click",()=>{const visible=i.type==="text";i.type=visible?"password":"text";b.textContent=visible?"Show":"Hide"})}
setupPasswordToggle("loginPasswordToggle","loginPassword");setupPasswordToggle("signupPasswordToggle","signupPassword");
loginForm.addEventListener("submit",e=>{e.preventDefault();const email=document.getElementById("loginEmail").value.trim(),password=document.getElementById("loginPassword").value;if(!email||!password){showMessage("Please enter your email and password.","error");return}localStorage.setItem("routa_logged_in","true");localStorage.setItem("routa_user_email",email);showMessage("Login successful. Opening dashboard...","success");setTimeout(()=>location.href="dashboard.html",700)});
signupForm.addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("signupName").value.trim(),role=document.getElementById("signupRole").value,email=document.getElementById("signupEmail").value.trim(),password=document.getElementById("signupPassword").value;if(!name||!role||!email||password.length<6){showMessage("Please complete all fields. Password must be at least 6 characters.","error");return}localStorage.setItem("routa_user_name",name);localStorage.setItem("routa_user_role",role);localStorage.setItem("routa_user_email",email);localStorage.setItem("routa_logged_in","true");showMessage("Account created successfully. Opening dashboard...","success");setTimeout(()=>location.href="dashboard.html",700)});
document.getElementById("forgotPasswordBtn").addEventListener("click",()=>showMessage("Password reset will be connected to the backend authentication system."));bindFooter();
